version: "3.8"
services:
  prime-number-server:
    build:
      context: ./prime-number-server
    ports:
      - "5000:5000"

  proxy-server:
    build:
      context: ./proxy-server
    ports:
      - "8080:8080"
    depends_on:
      - prime-number-server
